import 'package:tat/Widgets/Orders.dart';

class Elite {
  var products = {
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
    Orders(Products: 'Elite', Quantity: '0'),
  };
}
