import 'package:tat/Widgets/Orders.dart';

class Tata {
  var products = {
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
    Orders(Products: 'Salt', Quantity: '0'),
  };
}
